import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { cookies } from "next/headers";
import { themeKey } from "@/constants/theme.constants";
import { ClerkProvider } from "@clerk/nextjs";
import StoreProvider from "@/store/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Components Library",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get(themeKey);
  const theme = themeCookie?.value;

  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en" className="" suppressHydrationWarning>
        <body className={(inter.className, `dark:bg-semiblack`)}>
          <div className="z-0"></div>
          <Providers theme={theme!}>
            <StoreProvider>{children}</StoreProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
