import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { cookies } from "next/headers";
import { themeKey } from "@/constants/theme.constants";
import ThemeToggler from "@/components/pageComponents/theme-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get(themeKey);
  const theme = themeCookie?.value;

  return (
    <html
      lang="en"
      className="transition-colors duration-300"
      suppressHydrationWarning
    >
      <body
        className={
          (inter.className, `dark:bg-semiblack transition-colors duration-300`)
        }
      >
        <Providers theme={theme!}>{children}</Providers>
      </body>
    </html>
  );
}
